# Generated by Django 5.1.1 on 2024-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_management", "0002_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
